
import "./globals.css"
import Spline from "@splinetool/react-spline";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
}


export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body className="relative antialiased">
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100vw',
            height: '100vh',
            zIndex: -10,
            pointerEvents: 'none',
            userSelect: 'none',
          }}
        >
         
        </div>

        {/* Main Content */}
        <div className="relative z-10 min-h-screen">{children}</div>
      </body>
    </html>
  );
}






